name: ubuntu-k8s
summary: "ubuntu operating system"
description: "A popular operating system"
provides:
  ubuntu:
    interface: ubuntu
resources:
  ubuntu_image:
    type: "oci-image"
    description: "Image used for ubuntu pod."
series:
  - kubernetes
